<a href="https://colab.research.google.com/github/VincentGaoHJ/Course-CS5242/blob/master/practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PYTORCH TENSORS

WHAT IS PYTORCH?
It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- A deep learning research platform that provides maximum flexibility and speed

**Tensors**
Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.


In [4]:
# Run some setup code for this notebook.
import random
import numpy as np
import matplotlib.pyplot as plt

# This is a bit of magic to make matplotlib figures appear inline in the notebook
# rather than in a new window.
%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2
import torch
import torch.nn as nn

In [12]:
!nvidia-smi

Tue Jan 19 06:43:58 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    27W / 250W |     10MiB / 16280MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [18]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

Q1. Create a tensor “a” initialized from the list [2, 5, 8, 9]. Now print attributes of tensor  “a” i.e shape, dtype, device. Convert it to Numpy array “e”. 


In [27]:
tensor_lst = [2, 5, 8, 9]
a = torch.tensor(tensor_lst)
print(a)
print("shape: ", a.shape)
print("dtype: ", a.dtype)
print("device: ", a.device)

tensor([2, 5, 8, 9])
shape:  torch.Size([4])
dtype:  torch.int64
device:  cpu


In [28]:
e = a.numpy()
print(e)

[2 5 8 9]


Q2. Create a tensor “b” of size 4 * 5 initialized with all 0’s. Add 2 to “b”. Create another tensor “c” of the exact same as “b” initialized with all ones. Now create tensor “d = b + c”.

In [43]:
b = torch.from_numpy(np.zeros(20).reshape(4,5)) + 2
c = torch.from_numpy(np.ones(20).reshape(4,5))
d = b + c
print(d)

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]], dtype=torch.float64)


Q3. Create a Numpy array “f” of size 5 * 4 initialized with random numbers. Convert it to tensor “g”. Create “h” similar to “f” with random numbers. Transpose “h” and do matrix multiplication of “h” and “f”.

In [55]:
g, h = torch.from_numpy(np.random.rand(5,4)), torch.from_numpy(np.random.rand(5,4)).T
print('g:\n', g)
print('h:\n', h)
mm = torch.mm(g, h)
print('Matrix Multiplication g and h:\n',mm)

g:
 tensor([[0.1071, 0.3332, 0.0938, 0.2670],
        [0.8479, 0.4214, 0.3424, 0.3535],
        [0.9303, 0.9219, 0.8716, 0.1133],
        [0.5411, 0.8381, 0.1268, 0.8899],
        [0.7038, 0.1308, 0.2497, 0.8991]], dtype=torch.float64)
h:
 tensor([[0.7033, 0.5332, 0.8922, 0.8155, 0.0076],
        [0.5811, 0.3470, 0.5627, 0.8642, 0.6107],
        [0.2847, 0.4374, 0.2984, 0.9952, 0.2905],
        [0.8636, 0.4985, 0.5921, 0.0458, 0.8609]], dtype=torch.float64)
Matrix Multiplication g and h:
 tensor([[0.5262, 0.3468, 0.4691, 0.4809, 0.4614],
        [1.2439, 0.9243, 1.3051, 1.4126, 0.6676],
        [1.5359, 1.2536, 1.6759, 2.4280, 0.9208],
        [1.6721, 1.0784, 1.5190, 1.3326, 1.3188],
        [1.4184, 0.9780, 1.3083, 0.9766, 0.9317]], dtype=torch.float64)


Q4. Deep Learning is based on artificial neural networks which are typically built with units called "neurons”. Each neuron has some number of weighted inputs. These weighted inputs are summed together then passed through an activation function to get the unit's output.
	
1. Define a 1-D tensor “X” containing numbers from 1 to 5.
2. Define a 1-D tensor “W1” containing 5 random weights.
3. Define a tensor “b” contained 1 random weight.
4. Compute tensor “H = X * W1 + b” using pytorch. (Note the shape of tensors)
5. Apply sigmoid activation function to calculate the “Y”, such that “Y = 1 / (1 + exp(-H))”



In [ ]:
a.to(torch.device('cpu:0'))

tensor([2, 5, 8, 9])

In [103]:
# Define a 1-D tensor 'X' containing numbers from 1 to 5.
X = torch.tensor([range(1,6)]).float()
print("X:\n", X)

# Define a 1-D tensor "W1" containing 5 random weights.
W1 = torch.randn(1, 5)
print("W1:\n", W1)

# Define a tensor “b” contained 1 random weight.
b2 = torch.randn(1)
print("b:\n", b)

# Compute tensor “H = X * W1 + b” using pytorch. (Note the shape of tensors)
H = torch.mm(X, torch.transpose(W1, 0, 1)) + b
print("H = X * W1 + b:\n", H)

# Apply sigmoid activation function to calculate the “Y”, such that “Y = 1 / (1 + exp(-H))”
Y = 1 / (1 + torch.exp(-H))
print("Y = 1 / (1 + exp(-H)):\n", Y)

X:
 tensor([[1., 2., 3., 4., 5.]])
W1:
 tensor([[-1.8010, -1.1476,  1.1851,  0.2419,  0.5196]])
b:
 tensor([0.2028], dtype=torch.float64)
H = X * W1 + b:
 tensor([[3.2273]], dtype=torch.float64)
Y = 1 / (1 + exp(-H)):
 tensor([[0.9619]], dtype=torch.float64)


**You have just coded to write a neuron !!**

Q5. Adding multiple neurons in a single layer (3 Hidden Units)
1. Define 2-D tensor “W2” containing random numbers of shape 5 * 3
2. Define 1-D tensor of “b2” containing 3 random numbers.
3. Compute tensor H2 = [h1 h2 h3] using the “H2 = X * W2 + b2” using pytorch
4. Apply sigmoid activation function to calculate “Y2 = [y1 y2 y3]” such that “Y = 1 / (1 + exp(-H2)”


In [121]:
# Define 2-D tensor “W2” containing random numbers of shape 5 * 3
W2 = torch.randn(5, 3)
print("W2:\n", W2)

# Define 1-D tensor of “b2” containing 3 random numbers.
b2 = torch.randn(1, 3)
print("b2:\n", b2)

# Compute tensor H2 = [h1 h2 h3] using the “H2 = X * W2 + b2” using pytorch
H2 = torch.mm(X, W2) + b2
print("H2:\n", H2)

# Apply sigmoid activation function to calculate “Y2 = [y1 y2 y3]” such that “Y = 1 / (1 + exp(-H2)”
Y2 = 1 / (1 + torch.exp(-H2))
print("Y2:\n", Y2)

W2:
 tensor([[-1.4724e+00,  9.2126e-04,  1.1732e+00],
        [ 1.5458e+00, -2.3785e+00,  1.7613e+00],
        [ 1.5074e-02, -2.5566e-01,  8.4250e-01],
        [ 3.0760e+00,  1.3746e-01, -1.6280e-01],
        [-1.7259e+00, -3.1132e-01,  4.1290e-01]])
b2:
 tensor([[-0.1778,  0.2853,  0.4800]])
H2:
 tensor([[ 5.1611, -6.2446,  9.1165]])
Y2:
 tensor([[0.9943, 0.0019, 0.9999]])


**Now there are 3 neurons outputs!!**

Q6.  Stacking one neuron on top of others. The real power of a neural network comes when we apply one function on top of others. ( 3 output units)
1. Define 2-D tensor “W21” containing random numbers of shape 3 * 3
2. Define 1-D tensor “b3” containing 3 random number
3. Compute “H3 = W21 * Y2 + b”. Compute the expected shape of H3.
4. Apply softmax pytorch activation function to H3.


In [136]:
# Define 2-D tensor “W21” containing random numbers of shape 3 * 3
W21 = torch.randn(3, 3)
print("W21:\n", W21)

# Define 1-D tensor “b3” containing 3 random number
b3 = torch.randn(3)
print("b3:\n", b3)

# Compute “H3 = Y2 * W21 + b3”. Compute the expected shape of H3.
H3 = torch.mm(Y2, W21) + b3
print("H3:\n", H3)

# Apply softmax pytorch activation function to H3.
softmax = nn.Softmax(dim=1)
Y3 = softmax(H3)
print("Y3 using Pytorch Function:\n", Y3)

# Define a softmax activation function and apply it to H3
def softmax_func(input_tensor):
    exp_tensor = torch.exp(input_tensor)
    return exp_tensor/torch.sum(exp_tensor)
Y3 = softmax_func(H3)
print("Y3 using Own Defined Function:\n", Y3)

W21:
 tensor([[-1.1235, -0.1802, -0.3407],
        [ 0.5441, -0.6531,  0.1627],
        [-0.7861,  1.1294,  1.1717]])
b3:
 tensor([ 1.2272, -1.2689, -0.3881])
H3:
 tensor([[-0.6748, -0.3200,  0.4450]])
Y3 using Pytorch Function:
 tensor([[0.1821, 0.2597, 0.5581]])
Y3 using Own Defined Function:
 tensor([[0.1821, 0.2597, 0.5581]])


**Now there are 3 neurons outputs!!**